name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Build Reason
      run: echo ${{github.ref}} and ${{github.event_name}}
    - name: Build Content
      run: dotnet build ./Content/Vue.Simple.Template.sln -v quiet
    - name: Pack
      run: dotnet pack Vue.Simple.Project.Template.csproj -v quiet -o $NUPKGS --include-symbols
    - name: Publish Github Package
      run: dotnet nuget push "$NUPKGS/*.nupkg" --skip-duplicate --source $GH_FEED -k ${{ secrets.GH_PACKAGES_KEY }}
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  GH_FEED: github
  NUPKGS: ./.nupkgs
